Add of various languages
handikatriarlan/hello-world-in-every-language pull request #51
Opened 2024-10-03 20:40 UTC by AsrtoMichi

2024-10-03 20:57 UTC, AsrtoMichi reviewed
Comma removing

2024-10-04 07:00 UTC, handikatriarlan requested changes
bro that's too much 😭 but its okay. however you don't need to delete or update existing files. if the language is already in use, you can add a number at the end, e.g. hello_world_2.py

2024-10-04 09:06 UTC, AsrtoMichi reviewed
minor fix

2024-10-04 10:25 UTC, AsrtoMichi commented
> bro that's too much 😭 but its okay. however you don't need to delete or update existing files. if the language is already in use, you can add a number at the end, e.g. hello_world_2.py

I edited the files to standardize the output in Hello World!. And improve the names of langue, the language is C++ not cpp(it is the extension file).
Your project is very cool and I would like to contribute.
If you prefer I can make smaller pull requests.

2024-10-04 14:07 UTC, handikatriarlan commented
> > bro that's too much 😭 but its okay. however you don't need to delete or update existing files. if the language is already in use, you can add a number at the end, e.g. hello_world_2.py
> 
> I edited the files to standardize the output in Hello World!. And improve the names of langue, the language is C++ not cpp. Your project is very cool and I would like to contribute. If you prefer I can make smaller pull requests.

Okay tysm for helping to improve standardization in hello world code. I'll merge your pull request, you're doing great!

2024-10-04 14:08 UTC, merged